apiVersion: v1
kind: Service
metadata:
  labels:
    app: age-calculator
  name: age-calculator-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: age-calculator
  type: ClusterIP
